services:
  - type: web
    name: savemybill-ocr
    env: python
    rootDir: ocr-service
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn ocr:app
